/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectrental;

import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author user dell 7420
 */

public class dashboard extends javax.swing.JFrame {    
private java.awt.CardLayout cardLayout;
public hapusunit panelHapusunit;
private masterdata panelMasterdata;
private order panelOrder;
private tambahunit panelTambahunit;
private return1 panelReturn;
private income panelIncome;

 // Panel di bagian tengah frame

public dashboard() {
    initComponents();
 // Inisialisasi semua panel
    panelHapusunit = new hapusunit();
    panelOrder = new order();
    panelReturn = new return1();
    panelIncome = new income();
    panelMasterdata = new masterdata();
    panelTambahunit = new tambahunit();
    
    // Hubungkan cardLayout
    cardLayout = (CardLayout) ContentPanel.getLayout();
    
    // Tambahkan semua panel ke ContentPanel
    ContentPanel.add(panelMasterdata, "HalamanMaster");
    ContentPanel.add(panelOrder, "HalamanOrder");
    ContentPanel.add(panelReturn, "HalamanReturn");
    ContentPanel.add(panelIncome, "HalamanIncome");
    ContentPanel.add(panelHapusunit, "HalamanHapusUnit");
    ContentPanel.add(panelTambahunit, "HalamanTambahUnit");
    
    // Tampilkan default
    cardLayout.show(ContentPanel, "HalamanMaster");

}

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(dashboard.class.getName());

    /**
     * Creates new form dashboard
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mesinpencari = new javax.swing.JPanel();
        textmesinpencari = new javax.swing.JLabel();
        buttoncari = new javax.swing.JButton();
        helloadmin = new javax.swing.JLabel();
        buttonlogout = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        TambahUnit = new javax.swing.JButton();
        HapusUnit = new javax.swing.JButton();
        panelmenu = new javax.swing.JPanel();
        Master = new javax.swing.JButton();
        Order = new javax.swing.JButton();
        Return = new javax.swing.JButton();
        Income = new javax.swing.JButton();
        ContentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));

        textmesinpencari.setForeground(new java.awt.Color(204, 204, 204));
        textmesinpencari.setText("Masukkan Nama Mobil, ID, atau Jenis Transmisi");

        buttoncari.setText("Cari");

        javax.swing.GroupLayout mesinpencariLayout = new javax.swing.GroupLayout(mesinpencari);
        mesinpencari.setLayout(mesinpencariLayout);
        mesinpencariLayout.setHorizontalGroup(
            mesinpencariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mesinpencariLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textmesinpencari, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(buttoncari, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        mesinpencariLayout.setVerticalGroup(
            mesinpencariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mesinpencariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(textmesinpencari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttoncari))
        );

        helloadmin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        helloadmin.setForeground(new java.awt.Color(51, 51, 51));
        helloadmin.setText("HELLO, ARETA");

        buttonlogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonlogout.setText("Logout");
        buttonlogout.addActionListener(this::buttonlogoutActionPerformed);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua", "Matic", "Manual", "Termurah", "Termahal" }));

        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Filter Berdasarkan:");

        TambahUnit.setText("Tambah Unit");
        TambahUnit.addActionListener(this::TambahUnitActionPerformed);

        HapusUnit.setText("Hapus Unit");
        HapusUnit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HapusUnitMouseClicked(evt);
            }
        });
        HapusUnit.addActionListener(this::HapusUnitActionPerformed);

        panelmenu.setBackground(new java.awt.Color(255, 204, 102));

        Master.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Master.setText("Master Data");
        Master.addActionListener(this::MasterActionPerformed);

        Order.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Order.setText("Order");
        Order.addActionListener(this::OrderActionPerformed);

        Return.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Return.setText("Return");
        Return.addActionListener(this::ReturnActionPerformed);

        Income.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Income.setText("Income Sheet");
        Income.addActionListener(this::IncomeActionPerformed);

        javax.swing.GroupLayout panelmenuLayout = new javax.swing.GroupLayout(panelmenu);
        panelmenu.setLayout(panelmenuLayout);
        panelmenuLayout.setHorizontalGroup(
            panelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelmenuLayout.createSequentialGroup()
                .addGroup(panelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Master, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Order, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Return, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Income, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelmenuLayout.setVerticalGroup(
            panelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelmenuLayout.createSequentialGroup()
                .addComponent(Master, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Order, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Return, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Income, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(270, Short.MAX_VALUE))
        );

        ContentPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(helloadmin)
                                .addGap(309, 309, 309)
                                .addComponent(buttonlogout))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TambahUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(HapusUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(mesinpencari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 295, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(helloadmin)
                    .addComponent(buttonlogout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mesinpencari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TambahUnit)
                            .addComponent(HapusUnit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ContentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasterActionPerformed
    cardLayout.show(ContentPanel, "HalamanMaster");
    }//GEN-LAST:event_MasterActionPerformed

    private void TambahUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahUnitActionPerformed
     cardLayout.show(ContentPanel, "HalamanTambahUnit");
    }//GEN-LAST:event_TambahUnitActionPerformed

    private void OrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderActionPerformed
        panelOrder.loadPendingOrders();
        cardLayout.show(ContentPanel, "HalamanOrder");
    }//GEN-LAST:event_OrderActionPerformed

    private void HapusUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusUnitActionPerformed
        cardLayout.show(ContentPanel, "HalamanHapusUnit");
    }//GEN-LAST:event_HapusUnitActionPerformed

    private void ReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnActionPerformed
        panelReturn.loadActiveOrders();
        cardLayout.show(ContentPanel, "HalamanReturn");
    }//GEN-LAST:event_ReturnActionPerformed

    private void IncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncomeActionPerformed
    cardLayout.show(ContentPanel, "HalamanIncome");

    }//GEN-LAST:event_IncomeActionPerformed

    private void buttonlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonlogoutActionPerformed
           new Registrasi().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonlogoutActionPerformed

    private void HapusUnitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HapusUnitMouseClicked
    
        
    }//GEN-LAST:event_HapusUnitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new dashboard().setVisible(true));
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContentPanel;
    private javax.swing.JButton HapusUnit;
    private javax.swing.JButton Income;
    private javax.swing.JButton Master;
    private javax.swing.JButton Order;
    private javax.swing.JButton Return;
    private javax.swing.JButton TambahUnit;
    private javax.swing.JButton buttoncari;
    private javax.swing.JButton buttonlogout;
    private javax.swing.JLabel helloadmin;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel mesinpencari;
    private javax.swing.JPanel panelmenu;
    private javax.swing.JLabel textmesinpencari;
    // End of variables declaration//GEN-END:variables
}
