/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package projectrental;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user dell 7420
 */
public class income extends javax.swing.JPanel {

    /**
     * Creates new form income
     */
    public income() {
        initComponents();
        loadIncomeData();
        
        // Listener click baris tabel untuk memunculkan invoice
        tabelincome.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelincomeMouseClicked(evt);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelincome = new javax.swing.JTable();
        textincome = new javax.swing.JLabel();

        tabelincome.setAutoCreateRowSorter(true);
        tabelincome.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Order", "ID Mobil", "Mobil", "Transmisi", "Tanggal", "Waktu", "Periode", "Nominal", "PIC", "Title 10"
            }
        ));
        tabelincome.setCellSelectionEnabled(true);
        jScrollPane1.setViewportView(tabelincome);

        textincome.setBackground(new java.awt.Color(0, 255, 51));
        textincome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        textincome.setForeground(new java.awt.Color(102, 102, 102));
        textincome.setText("INVOICE TABEL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                    .addGap(11, 11, 11)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(251, 251, 251)
                    .addComponent(textincome)
                    .addContainerGap(252, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 373, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                    .addGap(17, 17, 17)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(178, 178, 178)
                    .addComponent(textincome)
                    .addContainerGap(179, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void loadIncomeData() {
        DefaultTableModel model = new DefaultTableModel(
            new String [] {
                "ID Order", "ID Mobil", "Mobil", "Transmisi", "Tanggal", "Waktu", "Periode", "Nominal", "PIC"
            }, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // read-only
            }
        };
        
        tabelincome.setModel(model);
        
        String sql = "SELECT r.id as order_id, r.car_id, c.brand, c.transmission, " +
                     "DATE_FORMAT(r.created_at, '%Y-%m-%d') as tanggal, " +
                     "DATE_FORMAT(r.created_at, '%H:%i:%s') as waktu, " +
                     "CONCAT(TIMESTAMPDIFF(HOUR, r.start_time, r.end_time), ' Jam') as periode, " +
                     "r.total_price, u.name as pic " +
                     "FROM rentals r " +
                     "JOIN cars c ON r.car_id = c.id " +
                     "LEFT JOIN users u ON r.admin_id = u.id " +
                     "WHERE r.status IN ('active', 'completed') " +
                     "ORDER BY r.updated_at DESC";
                     
        Connection conn = db.testdatabase.getKoneksi();
        if (conn == null) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Gagal menghubungkan ke database!\nPastikan MySQL server di XAMPP sudah dijalankan (Aktif).", 
                "Koneksi Database Gagal", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        try (Connection c = conn;
             PreparedStatement stmt = c.prepareStatement(sql);
             ResultSet rs = stmt.executeQuery()) {
             
            java.text.NumberFormat nf = java.text.NumberFormat.getCurrencyInstance(new java.util.Locale("id", "ID"));
            
            while (rs.next()) {
                int orderId = rs.getInt("order_id");
                int carId = rs.getInt("car_id");
                String brand = rs.getString("brand");
                String transmission = rs.getString("transmission");
                String tanggal = rs.getString("tanggal");
                String waktu = rs.getString("waktu");
                String periode = rs.getString("periode");
                double nominal = rs.getDouble("total_price");
                String pic = rs.getString("pic");
                if (pic == null) pic = "-";
                
                model.addRow(new Object[]{
                    orderId,
                    carId,
                    brand,
                    transmission,
                    tanggal,
                    waktu,
                    periode,
                    nf.format(nominal),
                    pic
                });
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal memuat data income:\n" + ex.getMessage(), "Error Database", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void tabelincomeMouseClicked(java.awt.event.MouseEvent evt) {
        int selectedRow = tabelincome.getSelectedRow();
        if (selectedRow != -1) {
            // Mengambil data dari baris yang dipilih
            String idOrder = tabelincome.getValueAt(selectedRow, 0).toString();
            String idMobil = tabelincome.getValueAt(selectedRow, 1).toString();
            String mobil = tabelincome.getValueAt(selectedRow, 2).toString();
            String transmisi = tabelincome.getValueAt(selectedRow, 3).toString();
            String tanggal = tabelincome.getValueAt(selectedRow, 4).toString();
            String waktu = tabelincome.getValueAt(selectedRow, 5).toString();
            String periode = tabelincome.getValueAt(selectedRow, 6).toString();
            String nominal = tabelincome.getValueAt(selectedRow, 7).toString();
            String pic = tabelincome.getValueAt(selectedRow, 8).toString();
            
            // Membuka JDialog invoices kustom secara terpisah
            java.awt.Frame parentFrame = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);
            invoices dialog = new invoices(parentFrame, true, idOrder, idMobil, mobil, transmisi, tanggal, waktu, periode, nominal, pic);
            dialog.setVisible(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelincome;
    private javax.swing.JLabel textincome;
    // End of variables declaration//GEN-END:variables
}
