package projectrental;

import db.testdatabase;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import org.mindrot.jbcrypt.BCrypt;

/**
 *
 * @author user dell 7420
 */
public class Registrasi extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Registrasi.class.getName());

    /**
     * Creates new form 
     */
    public Registrasi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        stringnomor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        stringemail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        stringpassword = new javax.swing.JPasswordField();
        buttonsignup = new javax.swing.JButton();
        switchbutton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        stringnomor.addActionListener(this::stringnomorActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Email");

        stringemail.addActionListener(this::stringemailActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Password");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("No. Telepon");

        buttonsignup.setText("Sign Up");
        buttonsignup.addActionListener(this::buttonsignupActionPerformed);

        switchbutton.setBackground(new java.awt.Color(242, 242, 242));
        switchbutton.setForeground(new java.awt.Color(0, 51, 204));
        switchbutton.setText("Back to Login Page");
        switchbutton.setBorder(null);
        switchbutton.setBorderPainted(false);
        switchbutton.setContentAreaFilled(false);
        switchbutton.addActionListener(this::switchbuttonActionPerformed);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("SIGN UP");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonsignup)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(stringemail)
                                .addComponent(stringnomor)
                                .addComponent(stringpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(switchbutton)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stringemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stringpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stringnomor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(buttonsignup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(switchbutton)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stringnomorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stringnomorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stringnomorActionPerformed

    private void switchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchbuttonActionPerformed
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_switchbuttonActionPerformed

    private void buttonsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonsignupActionPerformed
                                             
    // 1. Ambil input dari form GUI
    String email = stringemail.getText().trim();
    String password = new String(stringpassword.getPassword());
    String nomorTelepon = stringnomor.getText().trim();

    // 2. Validasi Input (Pastikan semua kolom terisi)
    if (email.isEmpty() || password.isEmpty() || nomorTelepon.isEmpty()) {
        JOptionPane.showMessageDialog(this, 
            "Semua kolom (Email, Password, dan No. Telepon) wajib diisi!", 
            "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Validasi format email sederhana
    if (!email.contains("@") || !email.contains(".")) {
        JOptionPane.showMessageDialog(this, 
            "Format email tidak valid!", 
            "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try (Connection conn = testdatabase.getKoneksi()) {
        // 3. Periksa apakah Email sudah digunakan di database
        String checkSql = "SELECT id FROM users WHERE email = ?";
        try (PreparedStatement checkStmt = conn.prepareStatement(checkSql)) {
            checkStmt.setString(1, email);
            try (ResultSet rs = checkStmt.executeQuery()) {
                if (rs.next()) {
                    JOptionPane.showMessageDialog(this, 
                        "Email sudah terdaftar! Gunakan email lain.", 
                        "Pendaftaran Gagal", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
        }

        // 4. Proses Hashing Password dengan BCrypt
        // gensalt() akan menghasilkan salt acak baru untuk keamanan ekstra
        String hashedPassword = BCrypt.hashpw(password, BCrypt.gensalt());

        // Ekstrak nama panggilan dari email (misal: "budi@gmail.com" -> "budi")
        String name = email.split("@")[0]; 

        // 5. Masukkan Data Admin Baru ke Database
        // role diatur default sebagai 'admin'
        String insertSql = "INSERT INTO users (name, email, password, role, phone, created_at, updated_at) "
                         + "VALUES (?, ?, ?, 'admin', ?, NOW(), NOW())";
                         
        try (PreparedStatement insertStmt = conn.prepareStatement(insertSql)) {
            insertStmt.setString(1, name);
            insertStmt.setString(2, email);
            insertStmt.setString(3, hashedPassword);
            insertStmt.setString(4, nomorTelepon);
            
            insertStmt.executeUpdate();

            // 6. Tampilkan Notifikasi Sukses
            JOptionPane.showMessageDialog(this, 
                "Registrasi Berhasil!\nAkun Admin telah didaftarkan. Silakan login kembali.", 
                "Sukses", JOptionPane.INFORMATION_MESSAGE);

            // 7. Arahkan kembali ke halaman Login
            new Login().setVisible(true);
            this.dispose(); // Tutup window registrasi
        }
        
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, 
            "Gagal melakukan registrasi:\n" + ex.getMessage(), 
            "Error Database", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }
     // TODO add your handling code here:
    }//GEN-LAST:event_buttonsignupActionPerformed

    private void stringemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stringemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stringemailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Registrasi().setVisible(true));
    
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonsignup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField stringemail;
    private javax.swing.JTextField stringnomor;
    private javax.swing.JPasswordField stringpassword;
    private javax.swing.JButton switchbutton;
    // End of variables declaration//GEN-END:variables
}